CXXFLAGS = --error-printer --abort-on-fail --have-eh

FLAGS = -Wall -g

graphexec.o:	graphexec.cpp grapgexec.h
	g++ $(FLAGS) -c graphexec.cpp 

clean:
	rm -Rf *.o *~ *DS_Store\
		assignment1 practice practiceIO
